### ISSUE TITLE
Mini not working 

### ISSUE THREAD

**Issue by johnmadri258** [harsha-0110/PPPwn-Luckfox#1]
Test on mini luckfox with SD card not working. No enough space

**Comment by harsha-0110** [comment]
Can you send the logs?

**Comment by harsha-0110** [comment]
> Test on mini luckfox with SD card not working. No enough space

Make sure to use SD card with storage of 8gb or more

**Comment by Doyle4** [comment]
My mini could do NAND and SD, NAND was smooth, but I tested using the SD method and also came into issues, make sure its a good SD card, one I used was pretty slow and thats what was causing timeout delays when connecting.
