### ISSUE TITLE
9.00 Payloads not showing

### ISSUE THREAD

**Issue by Doyle4** [harsha-0110/PPPwn-Luckfox#3]
Updated to latest build with all the 9.00 payloads, when going to 9.00 payloads using the web server, only the old ones are showing, things such as fan speed etc are not showing.

Thanks

**Comment by harsha-0110** [comment]
> Updated to latest build with all the 9.00 payloads, when going to 9.00 payloads using the web server, only the old ones are showing, things such as fan speed etc are not showing.
> 
> Thanks

Fixed it, check it out and let me know if any payload is not working. Thanks for pointing it out.

**Comment by Doyle4** [comment]
Thanks very much! Will test when I can and report back.

**Comment by Doyle4** [comment]
Working great thanks :)

**Comment by harsha-0110** [comment]
You're welcome
