### ISSUE TITLE
cp: write error: No space left on device

### ISSUE THREAD

**Issue by IRONB0SS** [harsha-0110/PPPwn-Luckfox#5]
LuckFox Pico Plus

![image](https://github.com/user-attachments/assets/1919ced9-6e0e-4f4e-92f6-dc4d121f36fb)

**Comment by harsha-0110** [comment]
Which image did you use?

**Comment by IRONB0SS** [comment]
> Which image did you use?

https://github.com/harsha-0110/PPPwn-Luckfox/releases/tag/v.1.1.1

**Comment by harsha-0110** [comment]
> > Which image did you use?
> 
> https://github.com/harsha-0110/PPPwn-Luckfox/releases/tag/v.1.1.1

I mean the image that you flashed on Luckfox Pico plus using the SocToolKit.

**Comment by IRONB0SS** [comment]
didn't flash anything, I used modded warfare youtube video and he said if you do not have sd card you can skip the 4 first steps

**Comment by IRONB0SS** [comment]
okay thanks

**Comment by harsha-0110** [comment]
You're welcome, you can follow the MODDEDWARFARE video, instead using the using the image provided in that video use the one the I provided, it should work.

**Comment by IRONB0SS** [comment]
![IMG_20240820_231846_223.jpg](https://github.com/user-attachments/assets/ee016ab2-ca5d-4af3-9350-ef05bcad7a41)

Sorry for being annoying person but what is this?

**Comment by IRONB0SS** [comment]
![20240821_000737.jpg](https://github.com/user-attachments/assets/946fcceb-715d-4681-b470-122374c770a2)

Another one 😬
