### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by GUNNERSx** [harsha-0110/PPPwn-Luckfox#9]
Hello!
before the Jailbreak web interface is quickly opened but once the jailbreak success it takes to long to access to the web interface sometimes it cant be opened.

I want to Thank you for this amazing job !

**Comment by harsha-0110** [comment]
You're welcome. Which version of PPPwn-Luckfox you are using?

**Comment by GUNNERSx** [comment]
I was on version PPPwn-LuckFox1.1.2 update to 1.1.3 yesterday but still same issue. 
I've tested 0x1iii1ii/PPPwn-Luckfox not fixed i switched back yo harsha-0110 since this one has more features. 
I'm using a LuckFox Pico Pro/Max.

**Comment by harsha-0110** [comment]
I have tested both my version and 0x1iii1ii's version, the web interface opens within few seconds after the successful jailbreak. You can try fresh installation by reflashing the img. And try using a different lan cable. I'll run few more tests to try reproduction the error your facing.

**Comment by harsha-0110** [comment]
If possible can you send your pppwn configuration and ps4 network configuration to try replicate the problem.

**Comment by GUNNERSx** [comment]
> If possible can you send your pppwn configuration and ps4 network configuration to try replicate the problem.

My [PS4 config](https://ibb.co/nRZ3bFv) but how can i get my pppwn config? 
i followed the tuto on yout repo to flash and configure my LuckFox!

**Comment by harsha-0110** [comment]
I'm not able to reproduce your problem. Perhaps, it could be problem with you luckfox or ps4.

**Comment by GUNNERSx** [comment]
> I'm not able to reproduce your problem. Perhaps, it could be problem with you luckfox or ps4.

Maybe !!
Thanks for all this job again !
